--
-- Routines for database 'Pixip'
--

DELIMITER ;;

/*!50003 DROP PROCEDURE IF EXISTS `sp_CreatePriceModels` */;;
/*!50003 SET SESSION SQL_MODE=""*/;;
/*!50003 CREATE*/ /*!50020 DEFINER=`openrate`@`localhost`*/ /*!50003 PROCEDURE `sp_CreatePriceModels`(
)
BEGIN
delete from RATE_PRICE_PIVOT;

-- Event based
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,0,1,SETUP_PRICE,1 from PRICE_MAP where RATING_TYPE = 'Event'
);

-- Duration based
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,999999,1,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Beat1'
);

--           ---------------
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,999999,1,RATE_PRICE,1 from PRICE_MAP where RATING_TYPE = 'Beat1PS'
);

--           ---------------
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,0,1,SETUP_PRICE,1 from PRICE_MAP where RATING_TYPE = 'Setup,Beat1'
);

insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,2,0,999999,1,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Setup,Beat1'
);

--           ---------------
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,0,1,SETUP_PRICE,1 from PRICE_MAP where RATING_TYPE = 'Setup,Beat60'
);

insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,2,0,999999,60,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Setup,Beat60'
);

--           ---------------
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,1,1,1,SETUP_PRICE,1 from PRICE_MAP where RATING_TYPE = 'Setup,Beat60,Beat1'
);

insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,2,0,60,60,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Setup,Beat60,Beat1'
);

insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,3,60,999999,1,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Setup,Beat60,Beat1'
);

--           ---------------
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,30,30,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Beat30,Beat1'
);

insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,2,30,999999,1,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Beat30,Beat1'
);

--           ---------------
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,60,60,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Beat60,Beat15'
);

insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,2,60,999999,15,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Beat60,Beat15'
);

--           ---------------
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,60,60,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Beat60,Beat30'
);

insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,2,60,999999,30,RATE_PRICE,60 from PRICE_MAP where RATING_TYPE = 'Beat60,Beat30'
);


-- Markup
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,1,1,1,SETUP_PRICE,1 from PRICE_MAP where RATING_TYPE = 'Setup,Markup'
);

insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,2,0,999999,0.01,RATE_PRICE,1 from PRICE_MAP where RATING_TYPE = 'Setup,Markup'
);

--           ---------------
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,999999,0.01,RATE_PRICE,1 from PRICE_MAP where RATING_TYPE = 'Markup'
);

-- Data
insert into RATE_PRICE_PIVOT (PRICE_MODEL,STEP,TIER_FROM,TIER_TO,BEAT,FACTOR,CHARGE_BASE)
(
  select distinct PRICE_GROUP,1,0,999999999,1,RATE_PRICE,1048576 from PRICE_MAP where RATING_TYPE = 'MBBeat1kB'
);


delete from PRICE_MODEL;
insert into PRICE_MODEL
(
  select * from RATE_PRICE_PIVOT
);

DELETE FROM RUM_MAP;
INSERT INTO RUM_MAP (PRICE_GROUP,PRICE_MODEL,RUM,RESOURCE,RESOURCE_ID,RUM_TYPE,CONSUME_FLAG,STEP)
(
  select distinct PRICE_GROUP,PRICE_GROUP,'DUR','MONEY',888,'TIERED',0,1 from PRICE_MAP where RATING_TYPE in ('Setup,Beat60,Beat1','Setup,Beat1','Beat1','Beat1PS','Beat30,Beat1','Beat60,Beat15','Beat60,Beat30','Setup,Beat60')
);

INSERT INTO RUM_MAP (PRICE_GROUP,PRICE_MODEL,RUM,RESOURCE,RESOURCE_ID,RUM_TYPE,CONSUME_FLAG,STEP)
(
  select distinct PRICE_GROUP,PRICE_GROUP,'VOL','MONEY',888,'TIERED',0,1 from PRICE_MAP where RATING_TYPE in ('MBBeat1kB')
);

INSERT INTO RUM_MAP (PRICE_GROUP,PRICE_MODEL,RUM,RESOURCE,RESOURCE_ID,RUM_TYPE,CONSUME_FLAG,STEP)
(
  select distinct PRICE_GROUP,PRICE_GROUP,'EVT','MONEY',888,'EVENT',0,1 from PRICE_MAP where RATING_TYPE in ('Event')
);

INSERT INTO RUM_MAP (PRICE_GROUP,PRICE_MODEL,RUM,RESOURCE,RESOURCE_ID,RUM_TYPE,CONSUME_FLAG,STEP)
(
  select distinct PRICE_GROUP,PRICE_GROUP,'SEK','MONEY',888,'TIERED',0,1 from PRICE_MAP where RATING_TYPE in ('Markup','Setup,Markup')
);

select concat(count(*),' price models created') from RUM_MAP;

END */;;

DELIMITER ;

