delete from PRICE_MAP where MAP_GROUP like 'ANYTIME%' and SERVICE in ('GPRS','SMS');

INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','GPRS','.*','.*','GPRS','.*','PMD_1','1 Per MB',1,0.0,'MBBeat1kB');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','GPRS','.*','.*','GPRS','.*','PMD_1','1 Per MB',1,0.0,'MBBeat1kB');

INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','SMS','.*','.*','NAL','.*','PME_0_7','0.7 Per Event',0.0,0.7,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','SMS','.*','.*','AE','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','SMS','.*','.*','Taiwan','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','SMS','.*','.*','ZAC','.*','PME_1','1 Per Event',0.0,1,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','SMS','.*','.*','UK','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','SMS','.*','.*','AE','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','SMS','.*','.*','AE','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 500','SMS','.*','.*','AB','.*','PME_0_7','0.7 Per Event',0.0,0.7,'Event');

INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','SMS','.*','.*','NAL','.*','PME_0_7','0.7 Per Event',0.0,0.7,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','SMS','.*','.*','AE','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','SMS','.*','.*','Taiwan','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','SMS','.*','.*','ZAC','.*','PME_1','1 Per Event',0.0,1,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','SMS','.*','.*','UK','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','SMS','.*','.*','AE','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','SMS','.*','.*','AE','.*','PME_1_3','1.3 Per Event',0.0,1.3,'Event');
INSERT INTO PRICE_MAP (MAP_GROUP,SERVICE,ORIGIN_ZONE,DEST_ZONE,ZONE_RESULT,TIME_RESULT,PRICE_GROUP,DESCRIPTION,RATE_PRICE,SETUP_PRICE,RATING_TYPE) VALUES ('ANYTIME 750','SMS','.*','.*','AB','.*','PME_0_7','0.7 Per Event',0.0,0.7,'Event');

call sp_CreatePriceModels();

